import { createHash } from 'node:crypto'
import {
  revenueCredentialAad,
  revenueObservationHash,
  type RevenueAdapter,
  type RevenueAdapterRegistry,
  type RevenueEventNormalization,
  type RevenueWebhookHeaders,
} from '@openanalytics/domain'
import type { CredentialVault } from '@openanalytics/integrations'
import {
  applyRevenueObservation,
  markRevenueProviderEvent,
  noteDisabledRevenueDelivery,
  readRevenueCredentialByWebhookToken,
  recordRevenueMatchHints,
  recordRevenueProviderEvent,
  updateRevenueCredentialState,
  type Database,
  type RevenueCredentialRow,
} from '@openanalytics/postgres'
import type { Logger } from '@openanalytics/observability'
import { Hono } from 'hono'
import type { ApiVariables } from './middleware.ts'
import { readCappedRawBody } from './raw-body.ts'

/**
 * The per-site revenue webhook (ADR-0033, D4).
 *
 * `POST /v1/revenue/webhooks/{provider}/{webhook_token}`, registered **before**
 * the session middleware exactly like the billing webhook: it is authenticated
 * by a signature over the raw body, and a route that reads `c.req.text()` cannot
 * sit behind anything that has already consumed the stream. The business subtree
 * owns `/v1` behind a blanket session guard, so a route registered after it
 * would 401 every delivery.
 *
 * ## Why the URL carries a token instead of a site id
 *
 * The opaque `webhook_token` is 32 random bytes minted at connect, unique across
 * the installation, and it resolves the credential *and* its site in one read.
 * That is what gives every customer their own endpoint under their own signing
 * secret — the property D1 chose over Stripe Connect, where every connected
 * account's events arrive on one platform endpoint under one shared secret and a
 * leak is every customer's problem rather than one site's.
 *
 * ## The order of the checks is the security model
 *
 * 1. **Resolve the token.** Unknown → 404. No ledger row, no log of the body.
 * 2. **Provider must match the path.** A token is bound to the credential that
 *    minted it; posting a Stripe payload to `/paddle/{same token}` is a 404
 *    rather than an attempt to normalize it with the wrong adapter.
 * 3. **Body size cap, before anything parses.** 1 MiB. A JSON parser is the
 *    first thing on this path that can be made to do unbounded work by an
 *    unauthenticated caller, and it must not be reached with an unbounded body.
 * 4. **Disabled credential → 200, ledgered `ignored`.** A disconnected site must
 *    not accumulate provider-side retry storms; Stripe disables an endpoint that
 *    keeps failing and emails the customer about it, which is a support ticket
 *    generated by our own tidiness.
 * 5. **Signature.** Invalid → 400, and **nothing is written**. A credential
 *    with no signing secret set yet (step one of the two-step connect, CP6)
 *    takes this exact branch: there is no signature that could be accepted, and
 *    a distinguishable answer would tell an unauthenticated caller which tokens
 *    are worth forging bodies against. This is the line
 *    between an authenticated body and an anonymous one: no ledger row, no
 *    credential timestamp, no object head. Everything below it may write.
 *
 * ## Failure semantics
 *
 * A failure that is *ours* — the provider unreachable during a tie-break
 * re-fetch — answers 5xx and **leaves the ledger row `received`**. Stripe
 * redelivers, the row is found unsettled, and the work is redone safely because
 * the apply layer is itself idempotent. Answering 200 there would be the M3
 * lesson unlearned: an acknowledged event is never redelivered, and the state it
 * carried would be lost for good (found in production on 2026-07-26).
 */

const REVENUE_WEBHOOK_PATH = '/revenue/webhooks/:provider/:webhook_token'

/**
 * There was a provider → signature-header-name map here. **The second provider
 * retired it**, exactly as the comment on it predicted.
 *
 * The map worked while a signature was one named header whose *value* was all an
 * adapter needed. Polar breaks both halves of that: it signs Standard Webhooks
 * style over three headers, and its event body carries **no id at all**, so the
 * `webhook-id` header is the delivery identity `revenue_provider_events` dedupes
 * on. A map of header names cannot express "and also the id is up here", and
 * growing it would have meant this transport layer learning each provider's
 * signing scheme — which is the one thing the adapter port exists to prevent.
 *
 * So the whole header set travels and the adapter picks. That is the same split
 * drawn everywhere else here: the transport carries bytes and resolves nothing,
 * the adapter owns semantics. Stripe's behaviour is unchanged — it reads
 * `stripe-signature` out of the set and hands the identical string to the
 * identical verifier — and the pipeline suites that were written against the map
 * still pass without an edit, which is the proof rather than the claim.
 */

/**
 * The body cap, applied before `JSON.parse` (D4).
 *
 * A Stripe event is a few kilobytes; the largest realistic one — an invoice with
 * hundreds of line items — is well under a hundred. A mebibyte is generous
 * enough that no legitimate delivery is ever refused and small enough that the
 * parser cannot be turned into a denial of service by anybody who learns a
 * token.
 */
export const REVENUE_WEBHOOK_MAX_BODY_BYTES = 1_048_576

export interface RevenueWebhookDeps {
  readonly db: Database
  /** Present by construction: this surface mounts only with a usable keyring,
   * because every delivery needs the signing secret decrypted. */
  readonly vault: CredentialVault
  readonly adapters: RevenueAdapterRegistry
  readonly logger?: Logger
  readonly maxBodyBytes?: number
}

export interface RevenueWebhookInput {
  readonly provider: string
  readonly webhookToken: string
  readonly rawBody: string
  /** A single pre-resolved signature header, for a caller that holds one. The
   * route no longer sets it; it passes `headers`. */
  readonly signatureHeader: string | undefined
  /** Every header of the delivery, lowercased. What the adapter actually reads —
   * see the note where the header-name map used to be. */
  readonly headers?: RevenueWebhookHeaders
  readonly now?: Date
}

export type RevenueWebhookResult =
  /** Acknowledged. `ledger` says what the row ended as; `short_circuit` is a
   * redelivery of an event already `processed`. */
  | {
      readonly status: 'ok'
      readonly ledger: 'processed' | 'ignored' | 'short_circuit'
      readonly reason?: string
    }
  | { readonly status: 'not_found' }
  | { readonly status: 'too_large' }
  | { readonly status: 'invalid_signature'; readonly reason: string }
  | { readonly status: 'malformed' }
  /** Ours, and retryable. The ledger row stays `received` on purpose. */
  | { readonly status: 'error'; readonly reason: string }

/**
 * Verify, dedupe and apply one delivery. Pure of Hono so it can be driven
 * directly in tests, exactly as `processStripeWebhook` is.
 */
export async function processRevenueWebhook(
  deps: RevenueWebhookDeps,
  input: RevenueWebhookInput,
): Promise<RevenueWebhookResult> {
  const now = input.now ?? new Date()
  const maxBytes = deps.maxBodyBytes ?? REVENUE_WEBHOOK_MAX_BODY_BYTES

  // Before the database is touched: a body too large to parse is refused
  // whether or not the token exists, so the cap costs one length check rather
  // than a round trip.
  if (Buffer.byteLength(input.rawBody, 'utf8') > maxBytes) {
    return { status: 'too_large' }
  }

  const credential = await readRevenueCredentialByWebhookToken(deps.db, input.webhookToken)
  if (!credential) return { status: 'not_found' }
  // The token is bound to the credential that minted it. A mismatch is a 404
  // rather than a 400: the two answers are indistinguishable to a caller who
  // guessed a token, which is the only caller that can produce one.
  if (credential.provider !== input.provider) return { status: 'not_found' }

  const adapter = deps.adapters.get(credential.provider)
  if (!adapter) {
    // The catalog says available and this build has no adapter — a packaging
    // mistake, ours, fixable by a deploy. 503 so the provider retries into the
    // fixed build rather than dropping deliveries into a build that cannot read
    // them.
    deps.logger?.error('revenue_webhook_adapter_missing', {
      site_id: credential.siteId,
      provider: credential.provider,
      retryable: true,
    })
    return { status: 'error', reason: 'adapter_unavailable' }
  }

  const payloadHash = sha256(input.rawBody)

  if (credential.status === 'disabled') {
    return await acknowledgeDisabled(deps, { credential, payloadHash, rawBody: input.rawBody, now })
  }

  if (credential.encryptedWebhookSecret === null) {
    // **No signing secret has been set yet** — the ordinary state between step
    // one and step two of the connect flow (CP6), not a fault.
    //
    // Answered as `invalid_signature`, byte for byte: 400, nothing written, no
    // ledger row. That is deliberate rather than lazy. The caller here is
    // unauthenticated by construction — anyone who guesses or learns a webhook
    // token can reach this line — and a distinguishable answer would be an
    // oracle telling them which sites have a signing secret configured, i.e.
    // which token is worth attacking with forged bodies and which is worth
    // simply flooding. There is no signature we could accept, so "we did not
    // accept your signature" is also the honest answer.
    //
    // Not ledgered, for the same reason the bad-signature path is not: the
    // ledger is a record of deliveries the provider signed, and an anonymous
    // body must not be able to write rows into it.
    deps.logger?.warn('revenue_webhook_no_signing_secret', {
      site_id: credential.siteId,
      provider: credential.provider,
      credential_id: credential.id,
      retryable: false,
    })
    return { status: 'invalid_signature', reason: 'no_signing_secret' }
  }

  const signingSecret = decryptSecret(deps, credential, credential.encryptedWebhookSecret)
  if (signingSecret === null) {
    // The ciphertext is present and UNREADABLE: a key removed from the ring, or
    // a row somebody rewrote. Distinct from the branch above — that one is the
    // customer mid-flow, this one is our keyring — and neither is decidable from
    // here nor the caller's fault, so it is a 5xx and the *credential status is
    // not touched*. The reconcile loop owns that transition — one writer of
    // `degraded`, and it must not be reachable by anyone who learns a token.
    deps.logger?.error('revenue_webhook_secret_undecryptable', {
      site_id: credential.siteId,
      credential_id: credential.id,
      key_version: credential.keyVersion,
      retryable: true,
    })
    return { status: 'error', reason: 'credential_undecryptable' }
  }

  const verified = adapter.verifyWebhook({
    rawBody: input.rawBody,
    signatureHeader: input.signatureHeader,
    ...(input.headers === undefined ? {} : { headers: input.headers }),
    signingSecret,
    now,
  })
  if (!verified.ok) {
    // Nothing is written. Everything above this line is a read; everything below
    // it acts on a body the provider signed.
    deps.logger?.warn('revenue_webhook_signature_rejected', {
      site_id: credential.siteId,
      provider: credential.provider,
      reason: verified.reason,
      retryable: false,
    })
    return { status: 'invalid_signature', reason: verified.reason }
  }

  let parsed: unknown
  try {
    parsed = JSON.parse(input.rawBody)
  } catch {
    // Signed and unparseable. Vanishingly unlikely and not retryable: the same
    // bytes will fail the same way, so 400 rather than 5xx.
    return { status: 'malformed' }
  }

  // The header set travels here too, and not for symmetry: for Polar the
  // event's own **identity** is a header (`webhook-id`) because the body carries
  // no id, and `providerEventId` below is what the ledger dedupes a redelivery
  // on. An adapter whose provider puts the id in the body ignores this.
  const normalized = adapter.normalizeEvent(parsed, {
    ...(input.headers === undefined ? {} : { headers: input.headers }),
  })
  if (!normalized.ok) return { status: 'malformed' }
  const event = normalized.event

  const recorded = await recordRevenueProviderEvent(deps.db, {
    siteId: credential.siteId,
    credentialId: credential.id,
    provider: credential.provider,
    providerEventId: event.eventId,
    payloadHash,
    source: 'webhook',
    now,
  })

  // A redelivery of an event already settled `processed` is acknowledged without
  // redoing the work. A row a crash left `received` — or one settled `ignored`,
  // whose reason may have changed with a build — is reprocessed, which is safe
  // because the object head below is itself idempotent.
  if (!recorded.firstSeen && recorded.status === 'processed') {
    await touchWebhookSuccess(deps, credential, now)
    return { status: 'ok', ledger: 'short_circuit' }
  }

  // Match hints, before the observations and independently of them (CP3, D6).
  //
  // A separate write on purpose: a hint has no money fields, so pushing it
  // through the object head would either tie on snapshot time — the charge is
  // created *by* the checkout, so their timestamps match — and cost a provider
  // request per checkout, or apply and rewrite the document that holds the
  // amounts. In its own table it cannot touch money at all.
  //
  // Stored raw. Hashing needs `ANONYMOUS_IDENTITY_SECRET`, which the worker
  // holds as of CP3 and this service deliberately does not, so the derivation
  // happens at projection time. Nothing here is an email.
  const hints = event.hints ?? []
  if (hints.length > 0) {
    await recordRevenueMatchHints(deps.db, {
      siteId: credential.siteId,
      provider: credential.provider,
      hints,
      now,
    })
  }

  if (event.observations.length === 0) {
    // A checkout event now *does* something, so it settles `processed` rather
    // than `ignored`: the two ledger states are read by an operator asking "why
    // is this site's revenue thin", and calling a stored matching signal
    // "ignored" would answer that question wrongly. An event that carried
    // neither observations nor hints is still `ignored`, with its own reason.
    const didSomething = hints.length > 0
    await markRevenueProviderEvent(deps.db, {
      id: recorded.id,
      status: didSomething ? 'processed' : 'ignored',
      result: didSomething
        ? { event_type: event.eventType, observations: 0, hints: hints.length }
        : { reason: event.ignored ?? 'no_observations', event_type: event.eventType },
      now,
    })
    await touchWebhookSuccess(deps, credential, now)
    return didSomething
      ? { status: 'ok', ledger: 'processed' }
      : { status: 'ok', ledger: 'ignored', reason: event.ignored ?? 'no_observations' }
  }

  const applied = await applyObservations(deps, { credential, adapter, event, now })
  if (!applied.ok) {
    // Deliberately no ledger settlement: the row stays `received`, the provider
    // redelivers, and the redelivery finds an unsettled row and tries again.
    deps.logger?.warn('revenue_webhook_refetch_failed', {
      site_id: credential.siteId,
      provider: credential.provider,
      event_type: event.eventType,
      reason: applied.reason,
      retryable: true,
    })
    return { status: 'error', reason: applied.reason }
  }

  await markRevenueProviderEvent(deps.db, {
    id: recorded.id,
    status: 'processed',
    result: {
      event_type: event.eventType,
      observations: event.observations.length,
      hints: hints.length,
      applied: applied.counts.applied,
      skipped: applied.counts.skipped,
      refetched: applied.counts.refetched,
    },
    now,
  })
  await touchWebhookSuccess(deps, credential, now)

  deps.logger?.info('revenue_webhook_processed', {
    site_id: credential.siteId,
    provider: credential.provider,
    event_type: event.eventType,
    applied: applied.counts.applied,
    skipped: applied.counts.skipped,
    refetched: applied.counts.refetched,
  })
  return { status: 'ok', ledger: 'processed' }
}

interface ApplyCounts {
  applied: number
  skipped: number
  refetched: number
}

type ApplyResult =
  | { readonly ok: true; readonly counts: ApplyCounts }
  | { readonly ok: false; readonly reason: string }

/**
 * Push each observation through the object head, resolving ties at the provider.
 *
 * The tie-break is the M3 rule at the object grain: equal snapshot time with a
 * *different* payload cannot be ordered from what we hold, so the authoritative
 * object is fetched and force-applied. `force` still refuses a strictly older
 * snapshot — the row lock was released for the network round-trip, and applying
 * an older state over a newer one is the revert ADR-0021 had to fix on the
 * billing side.
 */
async function applyObservations(
  deps: RevenueWebhookDeps,
  input: {
    credential: RevenueCredentialRow
    adapter: RevenueAdapter
    event: RevenueEventNormalization
    now: Date
  },
): Promise<ApplyResult> {
  const counts: ApplyCounts = { applied: 0, skipped: 0, refetched: 0 }
  const { credential, adapter } = input
  // Decrypted lazily: the overwhelming majority of deliveries never tie, and a
  // plaintext provider key held for the length of every webhook request is a
  // secret in memory for no reason.
  let apiKey: string | null | undefined

  for (const observation of input.event.observations) {
    const decided = await applyRevenueObservation(deps.db, {
      siteId: credential.siteId,
      provider: credential.provider,
      observation,
      payloadHash: revenueObservationHash(observation.normalized),
      now: input.now,
    })

    if (decided.decision.action === 'apply') {
      counts.applied += 1
      continue
    }
    if (decided.decision.action === 'skip') {
      counts.skipped += 1
      continue
    }

    if (apiKey === undefined) apiKey = decryptSecret(deps, credential, credential.encryptedApiKey)
    if (apiKey === null) return { ok: false, reason: 'credential_undecryptable' }

    const fetched = await adapter.fetchObject(apiKey, observation.objectKind, observation.objectId)
    if (!fetched.ok) return { ok: false, reason: `provider_${fetched.reason}` }
    if (fetched.observation === null) {
      // The provider has forgotten the object. There is nothing authoritative to
      // apply and never will be, so the tie resolves as a skip rather than as a
      // retry that could not succeed.
      counts.skipped += 1
      continue
    }

    const forced = await applyRevenueObservation(deps.db, {
      siteId: credential.siteId,
      provider: credential.provider,
      observation: fetched.observation,
      payloadHash: revenueObservationHash(fetched.observation.normalized),
      force: true,
      now: input.now,
    })
    counts.refetched += 1
    if (forced.decision.action === 'apply') counts.applied += 1
    else counts.skipped += 1
  }

  return { ok: true, counts }
}

/**
 * Acknowledge a delivery to a disconnected credential.
 *
 * 200 so the provider stops retrying and does not disable the customer's
 * endpoint on our behalf, plus a ledger row so "your disconnected provider is
 * still sending us events" is answerable rather than invisible.
 *
 * This is the one place in this file where an unauthenticated body reaches a
 * write, and it is bounded to **one row per credential, ever**. A disabled
 * credential has no signing secret left to verify against — disconnect erases
 * both ciphertexts in one UPDATE — so either nothing is recorded or something
 * unverified is.
 *
 * Keying the row on the *payload hash* would have let anybody holding the old
 * URL insert a fresh row per distinct body by varying a single byte. Keying it
 * on the **credential** means the first delivery inserts and every later one
 * increments a counter in `result`. What an operator needs — "your disconnected
 * provider is still posting, and it has done so N times" — survives intact, and
 * the write amplification available to an unauthenticated caller is one UPDATE
 * of one row.
 */
async function acknowledgeDisabled(
  deps: RevenueWebhookDeps,
  input: {
    credential: RevenueCredentialRow
    payloadHash: string
    rawBody: string
    now: Date
  },
): Promise<RevenueWebhookResult> {
  const noted = await noteDisabledRevenueDelivery(deps.db, {
    siteId: input.credential.siteId,
    credentialId: input.credential.id,
    provider: input.credential.provider,
    payloadHash: input.payloadHash,
    now: input.now,
  })

  deps.logger?.info('revenue_webhook_disabled_credential', {
    site_id: input.credential.siteId,
    provider: input.credential.provider,
    deliveries: noted.deliveries,
  })
  // `last_webhook_at` is deliberately NOT touched: it is the read surface's
  // "this connection is alive" signal, and a disconnected credential is not.
  return { status: 'ok', ledger: 'ignored', reason: 'credential_disabled' }
}

/**
 * Record that a delivery landed, and that the connection works.
 *
 * A **successful webhook on a `degraded` credential flips it back to `active`**
 * (D4). Degraded means "the last thing we tried failed"; a signed delivery we
 * verified, normalized and applied is direct evidence that the customer's
 * endpoint and our processing both work, and leaving the badge lit would keep
 * telling a customer their integration is broken while it demonstrably is not.
 * `last_error` is cleared with it, because a stale category renders to the
 * customer as an outage they cannot fix.
 *
 * `last_synced_at` is untouched: it means "the sync loop last read the provider
 * successfully", which a webhook is not. Conflating them would fabricate
 * freshness for a credential whose API key has been revoked.
 */
async function touchWebhookSuccess(
  deps: RevenueWebhookDeps,
  credential: RevenueCredentialRow,
  now: Date,
): Promise<void> {
  await updateRevenueCredentialState(deps.db, {
    credentialId: credential.id,
    siteId: credential.siteId,
    lastWebhookAt: now,
    ...(credential.status === 'degraded' ? { status: 'active' as const, lastError: null } : {}),
    now,
  })
}

/** Decrypt one of the row's ciphertexts, or null. Never logs the value. */
function decryptSecret(
  deps: RevenueWebhookDeps,
  credential: RevenueCredentialRow,
  stored: string | null,
): string | null {
  if (stored === null) return null
  const aad = revenueCredentialAad({ credentialId: credential.id, siteId: credential.siteId })
  const outcome = deps.vault.decrypt(stored, aad)
  return outcome.ok ? outcome.plaintext : null
}

function sha256(value: string): string {
  return createHash('sha256').update(value).digest('hex')
}

type Env = { Variables: ApiVariables }

/**
 * The route.
 *
 * Answers plain JSON rather than the `ApiError` envelope, exactly as the billing
 * webhook does: the reader is a provider's delivery machinery, which acts on the
 * status code and logs the body verbatim into a dashboard the customer can see.
 * A structured error envelope there would put our internal error vocabulary in
 * front of somebody debugging their own Stripe account.
 */
export function createRevenueWebhookRoutes(deps: RevenueWebhookDeps): Hono<Env> {
  const app = new Hono<Env>()

  app.post(REVENUE_WEBHOOK_PATH, async (c) => {
    const provider = c.req.param('provider')
    const maxBytes = deps.maxBodyBytes ?? REVENUE_WEBHOOK_MAX_BODY_BYTES
    // The cap binds on `Content-Length` **before** the body is buffered, and
    // again on the buffered length for a chunked or lying request. Reading first
    // and checking afterwards would let an unauthenticated caller decide how
    // much memory this process allocates.
    const raw = await readCappedRawBody(c.req, maxBytes)
    if (!raw.ok) return c.json({ received: false }, 413)

    const requestLogger = deps.logger ?? c.get('logger')
    const result = await processRevenueWebhook(
      { ...deps, ...(requestLogger ? { logger: requestLogger } : {}) },
      {
        provider,
        webhookToken: c.req.param('webhook_token'),
        rawBody: raw.body,
        // Nothing is resolved here any more. Hono lowercases header names, which
        // is the form every adapter reads and the form the port documents.
        signatureHeader: undefined,
        headers: c.req.header(),
      },
    )

    switch (result.status) {
      case 'ok':
        return c.json({ received: true }, 200)
      case 'not_found':
        return c.json({ received: false }, 404)
      case 'too_large':
        return c.json({ received: false }, 413)
      case 'invalid_signature':
        return c.json({ received: false }, 400)
      case 'malformed':
        return c.json({ received: false }, 400)
      case 'error':
        // 503, so the provider retries. The ledger row is still `received`.
        return c.json({ received: false }, 503)
    }
  })

  return app
}
