export {
  CLOUD_MIGRATIONS_TABLE,
  MIGRATIONS_TABLE,
  migratePostgres,
  type MigrateResult,
  type PostgresMigrateOptions,
} from './migrate.ts'

export { newId, uuidv7 } from './ids.ts'
export { createDatabase, createPool, type Database, type Executor, type Schema } from './client.ts'
export * as schema from './schema/index.ts'
// `cloudSchema` and `cloudSchemaTableColumns` were re-exported here until the
// open-core boundary was enforced. Both are on `@openanalytics/postgres/cloud`
// now — a product barrel that re-exported them made every consumer of this
// package a consumer of the hosted schema.
export { schemaTableColumns, tableColumnsOf, type TableColumns } from './introspect.ts'
export {
  claimDueOutbox,
  enqueueOutbox,
  markOutboxDelivered,
  markOutboxFailed,
  readOutboxBacklog,
  readOutboxDelivery,
  reclaimStalledOutbox,
  type ClaimedOutboxRow,
  type OutboxBacklogRow,
  type OutboxDeliveryRow,
  type EnqueueOutboxInput,
  type EnqueueOutboxResult,
  type MarkOutboxFailedOptions,
  type ReclaimStalledOutboxOptions,
} from './repositories/outbox.ts'

export {
  clearDeploymentSetting,
  deploymentOperatorUserId,
  readDeploymentSetting,
  writeDeploymentSetting,
  type DeploymentSettingRow,
  type WriteDeploymentSettingInput,
} from './repositories/deployment-settings.ts'

export type {
  AssistantDeploymentSettings,
  DeploymentSettingScope,
  EmailDeploymentSettings,
} from './schema/deployment-settings.ts'

export {
  OwnershipError,
  SITE_OWNERSHIP_CHANGED_TOPIC,
  addMember,
  countOwners,
  createSite,
  createSiteWithOwner,
  getMembership,
  getSiteBasics,
  getSiteForUser,
  listMembers,
  listSitesForUser,
  markSitesFirstEvent,
  removeMember,
  resolveSlugForUser,
  updateMemberRole,
  updateSiteSettings,
  type AddMemberInput,
  type CreateSiteInput,
  type CreateSiteWithOwnerInput,
  type CreateSiteWithOwnerResult,
  type CreatedSite,
  type CreatedSiteTrackingKey,
  type OwnershipViolation,
  type SiteBasics,
  type SiteFirstEventCandidate,
  type SiteForUser,
  type SiteMemberSummary,
  type UpdateMemberRoleInput,
  type UpdateSiteSettingsInput,
  type UpdatedMemberRole,
  type UpdatedSiteSettings,
  mapOwnershipError,
  registerSiteCreateExtension,
  type SiteCreateExtension,
} from './repositories/sites.ts'

export {
  registerOwnershipTransferExtension,
  transferSiteOwnership,
  type OwnershipTransferContext,
  type OwnershipTransferExtension,
  type SiteOwnerTransferMode,
  type SiteOwnerTransferResult,
} from './repositories/site-ownership.ts'

export {
  ACCOUNT_DELETION_JOB_TYPE,
  SITE_DELETION_JOB_TYPE,
  claimDueJobs,
  completeJob,
  enqueueJob,
  extendJobLease,
  failJobRetryable,
  readJobStatusByIdempotencyKey,
  readJobsBacklog,
  updateJobPhase,
  type ClaimDueJobsInput,
  type ClaimedJob,
  type EnqueueJobInput,
  type EnqueueJobResult,
  type JobsBacklogRow,
  type TerminalJobStatus,
} from './repositories/jobs.ts'

export type { JobStatus } from './schema/lifecycle.ts'

export {
  ACCOUNT_DELETION_COMPLETED_TOPIC,
  AccountDeletionBlockedError,
  accountTombstoneEmail,
  finalizeAccountDeletion,
  listBilledSiteStates,
  markAccountDeletionFailed,
  markAccountDeletionRunning,
  purgeAccountPostgres,
  readAccountDeletionContext,
  startAccountDeletion,
  type AccountDeletionBlockReason,
  type AccountDeletionBlocker,
  type AccountDeletionContext,
  type AccountDeletionJobPayload,
  type BilledSiteState,
  type FinalizeAccountDeletionInput,
  type PurgeAccountPostgresResult,
  type StartAccountDeletionInput,
  type StartAccountDeletionResult,
  registerAccountDeletionExtension,
  type AccountTargetProbe,
  type AccountTeardownStep,
} from './repositories/account-deletion.ts'

export {
  FINALIZABLE_SITE_STATUSES,
  SITE_DELETION_COMPLETED_TOPIC,
  SiteDeletionError,
  countInFlightWriters,
  filterFinalizableSites,
  finalizeSiteDeletion,
  listDeletionTargets,
  listSiteMemberUserIds,
  listSiteStatuses,
  markDeletionRequestRunning,
  markSiteDeletionFailed,
  purgeSitePostgres,
  readSiteDeletionContext,
  startSiteDeletion,
  updateDeletionTarget,
  type DeletionTargetRow,
  type FinalizeSiteDeletionInput,
  type MarkSiteDeletionFailedInput,
  type PurgeSitePostgresResult,
  type SiteDeletionContext,
  type SiteDeletionJobPayload,
  type SiteDeletionReason,
  type StartSiteDeletionInput,
  type StartSiteDeletionResult,
  type UpdateDeletionTargetInput,
  registerSitePurgeStep,
  type SitePurgeStep,
} from './repositories/site-deletion.ts'

export {
  IMPORT_PREPARE_JOB_TYPE,
  IMPORT_PUBLISH_JOB_TYPE,
  claimImportRunForCleanup,
  clearStagingProgress,
  createImportRun,
  findLiveImportRunId,
  listCleanableImportRuns,
  listCleanableSiteImportRuns,
  listExpiredImportUploads,
  listImportRuns,
  listSiteImportObjectKeys,
  pinUploadEtag,
  publishImportRun,
  readImportRun,
  readImportUpload,
  readSiteImportContext,
  recordStagingChunkBytes,
  recordStagingProgress,
  releaseImportRunCleanupClaim,
  rollbackImportRun,
  transitionImportRun,
  type CleanableImportRun,
  type CreateImportRunInput,
  type CreateImportRunResult,
  type ExpiredImportUpload,
  type ImportRunRow,
  type ImportUploadRow,
  type PublishImportRunResult,
  type RollbackImportRunResult,
  type SiteImportContext,
  type TransitionImportRunInput,
} from './repositories/import-runs.ts'

export {
  EXPORT_RUN_JOB_TYPE,
  claimExportDownload,
  completeExportRun,
  createExportRun,
  exportRunJobKey,
  failExportRun,
  findLiveExportRunId,
  listExportRuns,
  listSiteExportObjectKeys,
  readExportRun,
  recordExportChunk,
  retractExportChunks,
  startExportRun,
  type ClaimExportDownloadInput,
  type CreateExportRunInput,
  type CreateExportRunResult,
  type ExportDownloadResult,
  type ExportRunRow,
} from './repositories/export-runs.ts'

export {
  createRevenueCredential,
  disconnectRevenueCredential,
  eraseSiteRevenueCredentials,
  mintWebhookToken,
  readLiveRevenueCredential,
  readRevenueCredential,
  readRevenueCredentialByWebhookToken,
  revokeAccountRevenueCredentials,
  revokeRevenueCredentialsCreatedBy,
  rotateRevenueCredential,
  setRevenueWebhookSecret,
  updateRevenueCredentialState,
  type CreateRevenueCredentialInput,
  type CreateRevenueCredentialResult,
  type DisconnectRevenueCredentialInput,
  type ReadRevenueCredentialInput,
  type RevenueCredentialRow,
  type RevokeRevenueCredentialsInput,
  type RotateRevenueCredentialInput,
  type SetRevenueWebhookSecretInput,
  type UpdateRevenueCredentialStateInput,
} from './repositories/revenue-credentials.ts'

export {
  REVENUE_BACKFILL_JOB_TYPE,
  REVENUE_STUCK_DELIVERY_REASON,
  REVENUE_UNAUTHORIZED_ERROR,
  applyRevenueObservation,
  enqueueRevenueBackfill,
  failStuckRevenueDeliveries,
  listRevenueCredentialsDueForSync,
  listSitesWithUnprojectedRevenue,
  listUnprojectedRevenueObjects,
  markRevenueObjectsProjected,
  markRevenueProviderEvent,
  noteDisabledRevenueDelivery,
  readOldestUnprojectedRevenueChange,
  readRevenueObject,
  readRevenueProviderEvent,
  readRevenueSyncState,
  readSiteReportingCurrency,
  recordRevenueProviderEvent,
  requestRevenueBackfill,
  resetRevenueProjection,
  saveRevenueSyncState,
  type AppliedRevenueObservation,
  type ApplyRevenueObservationInput,
  type DueRevenueCredential,
  type RecordRevenueEventInput,
  type RecordedRevenueEvent,
  type RequestRevenueBackfillResult,
  type RevenueObjectHeadRow,
  type RevenueSyncStateRow,
  type SaveRevenueSyncStateInput,
  type UnprojectedRevenueObject,
} from './repositories/revenue-objects.ts'

export {
  readRevenueMatchHint,
  readRevenueMatchHintsByOrder,
  recordRevenueMatchHints,
  type RecordRevenueMatchHintsInput,
  type RecordRevenueMatchHintsResult,
  type RevenueMatchHintRow,
} from './repositories/revenue-match-hints.ts'

export {
  advanceRevenueAttributionWatermark,
  advanceRevenueRollupRecompute,
  claimRevenueAttributionSite,
  getRevenueAttributionState,
  isSiteFullyProjected,
  listSitesForRevenueAttribution,
  markRevenueRollupRecompute,
  readOldestChangedRevenueChargeOccurrence,
  readOldestChangedRevenueObjectOccurrence,
  readOldestRevenueAttributionWatermark,
  releaseRevenueAttributionSite,
  type RevenueAttributionClaim,
  type RevenueAttributionStateRow,
} from './repositories/revenue-attribution.ts'

export {
  readCurrencyRate,
  readLatestCurrencyRateDate,
  upsertCurrencyRates,
  type CurrencyRateRow,
  type UpsertCurrencyRatesResult,
} from './repositories/currency-rates.ts'

export {
  claimIdempotencyKey,
  completeIdempotencyKey,
  releaseIdempotencyKey,
  sweepIdempotencyKeys,
  type ClaimIdempotencyKeyInput,
  type CompleteIdempotencyKeyInput,
  type IdempotencyClaim,
  type IdempotencyKeyRef,
  type SweepIdempotencyKeysInput,
} from './repositories/idempotency.ts'

export {
  writeAudit,
  type AuditActorType,
  type AuditEntry,
  type AuditExecutor,
} from './repositories/audit.ts'

export {
  getAuthedUserById,
  getUserPreferences,
  hasAnyUser,
  markUserEmailVerified,
  setUserTimezone,
  type AuthedUserRow,
  type SetUserTimezoneInput,
  type UserPreferences,
} from './repositories/users.ts'

export {
  generateShareSlug,
  getPublicDashboardSettings,
  isSharePublishing,
  isSurfaceShared,
  PUBLIC_SURFACES,
  readPublicSiteIdentity,
  resolvePublicShare,
  updatePublicDashboardSettings,
  type PublicDashboardSettings,
  type PublicSiteIdentity,
  type PublicSurface,
  type PublicSurfaceFlags,
  type ResolvedPublicShare,
  type UpdatePublicDashboardInput,
} from './repositories/public-dashboard.ts'

export {
  listSiteDomains,
  readSiteIngestSettings,
  resolveIngestConfig,
  upsertSiteIngestSettings,
  type ResolvedIngestConfig,
  type ResolvedNoCodeRule,
  type UpsertSiteIngestSettingsInput,
} from './repositories/ingest-config.ts'

export {
  applyDepartureToApiKeys,
  createApiKey,
  getLiveTrackingToken,
  listApiKeys,
  resolveReadApiKey,
  resolveTrackingKey,
  revokeApiKey,
  touchApiKeyUsage,
  type ApiKeySummary,
  type ApiKeyType,
  type CreateApiKeyInput,
  type CreatedApiKey,
  type ResolvedApiKey,
} from './repositories/api-keys.ts'

export { chargeReadCost, readCostSpent, sweepReadCostLedger } from './repositories/read-cost.ts'

export {
  noteCredentialSource,
  type CredentialKindValue,
  type CredentialSourceOutcome,
  type NoteCredentialSourceInput,
  type NoteCredentialSourceResult,
} from './repositories/credential-sources.ts'

export {
  assistantQuestionsSpent,
  chargeAssistantQuestion,
  readAssistantUsage,
  recordAssistantTokens,
  sweepAssistantUsageLedger,
  type AssistantUsageWindow,
} from './repositories/assistant-usage.ts'

export {
  claimApprovedDeviceCode,
  createOAuthApplication,
  findDeviceAuthorization,
  findOAuthApplicationName,
  issueOAuthAccessToken,
  listConnectedApps,
  resolveOAuthAccessToken,
  revokeConnectedApp,
  sweepExpiredDeviceCodes,
  type ConnectedApp,
  type CreatedOAuthApplication,
  type DeviceAuthorizationView,
  type DeviceExchangeResult,
  type IssuedOAuthToken,
  type ResolvedOAuthToken,
} from './repositories/oauth.ts'

export {
  archiveFunnel,
  createFunnel,
  getFunnel,
  listFunnels,
  updateFunnel,
  type CreateFunnelInput,
  type FunnelDefinition,
  type ListFunnelsOptions,
  type UpdateFunnelInput,
} from './repositories/funnels.ts'

export {
  countWidgets,
  createWidget,
  deleteWidget,
  generateWidgetId,
  getWidget,
  listWidgets,
  resolvePublicWidget,
  updateWidget,
  type CreateWidgetInput,
  type ResolvedPublicWidget,
  type UpdateWidgetInput,
  type WidgetRecord,
} from './repositories/widgets.ts'

export {
  archiveEventDefinition,
  createEventDefinition,
  getEventDefinition,
  getEventDefinitionVersion,
  listEventDefinitionVersions,
  listEventDefinitions,
  listEventDisplayNames,
  listPublishedRules,
  publishEventDefinition,
  rollbackEventDefinition,
  saveEventDefinitionVersion,
  type CreateEventDefinitionInput,
  type EventDefinitionRecord,
  type EventDefinitionVersionContent,
  type EventDefinitionVersionRecord,
  type EventDisplayRecord,
  type ListEventDefinitionsOptions,
  type PublishEventDefinitionInput,
  type PublishOutcome,
  type PublishedRuleRecord,
  type RollbackEventDefinitionInput,
  type RollbackOutcome,
  type SaveEventDefinitionVersionInput,
} from './repositories/event-definitions.ts'

export {
  EXPIRED_INVITE_VISIBLE_DAYS,
  INVITE_TTL_HOURS,
  InviteError,
  acceptInvite,
  createInvite,
  expireStaleInvites,
  listSiteInvites,
  resendInvite,
  revokeInvite,
  type AcceptInviteInput,
  type AcceptedInvite,
  type CreateInviteInput,
  type CreatedInvite,
  type InviteViolation,
  type ListedInviteStatus,
  type ResendInviteInput,
  type ResentInvite,
  type RevokeInviteInput,
  type SiteInviteSummary,
} from './repositories/invites.ts'

export {
  ManifestTransitionError,
  claimManifest,
  createOrContinueManifest,
  deleteManifestsCompletedBefore,
  getManifest,
  listBatchSites,
  listBatchesCompletedAfter,
  listCompletedBatchLedgerTotals,
  listRecentlyIngestedSites,
  listRunnableManifests,
  markAttemptFailed,
  markBatchSitesWritten,
  markCompleted,
  markDeadLettered,
  markInserted,
  markInserting,
  markUsageRecorded,
  registerBatchSites,
  replayDeadLettered,
  type BatchLedgerTotal,
  type CreateManifestInput,
  type FenceDecision,
  type FenceRegistration,
  type Manifest,
  type ManifestItem,
  type ManifestMessage,
  type ManifestPlan,
} from './repositories/ingest-batches.ts'

export {
  advanceFinalizerWatermark,
  claimFinalizerSite,
  getFinalizerState,
  releaseFinalizerSite,
  type FinalizerClaim,
  type FinalizerStateRow,
} from './repositories/session-finalizer.ts'

export {
  INGEST_PIPELINE_ID,
  getWorkerHeartbeat,
  upsertWorkerHeartbeat,
  type UpsertWorkerHeartbeatInput,
  type WorkerHeartbeat,
} from './repositories/worker-heartbeats.ts'

export {
  applyBatchUsage,
  readBatchLedgerTotal,
  type AppliedUsage,
  type UsageDelta,
  registerUsageLedgerExtension,
  type UsageLedgerExtension,
} from './repositories/usage.ts'
